### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by jeanchristophehenry**
Add ruby for use gem and install bundler for use bundle exec fastlane :)

# Summary

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |

## Checklist

- [x] I have tested this on a device and a simulator
- [x] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by gengjiawen** [comment]
Is there any data I can check how much devs use fastlane ?

**Comment by timkuilman** [comment]
There's at least one here. I'm looking forward for this PR to get merged. Currently I'm installing Ruby and bundler as an separate step in my CircleCI setup.

**Comment by gengjiawen** [comment]
The size increase 73M, I think we can do with that.

**Comment by jchenry-erudo** [comment]
**Hello**, that's a good question. I created an image in docker hub for my runners for **Android** on **gitlab**-**ci**
[Image Docker-hub](https://hub.docker.com/r/jeanchristophehenry/ynov-docker-android)
It's possible use **fastlane** with **Codemagic**.

[Fastlane gems](https://rubygems.org/gems/fastlane) 22Millions download 

[Fastlane github](https://github.com/fastlane/fastlane/stargazers) Used 8.500 | Watch 715 | Star 27,392 | Fork 4,200

**Comment by jeanchristophehenry** [comment]
**Hello**, that's a good question. I created an image in docker hub for my runners for **Android** on **gitlab**-**ci**
It's possible use **fastlane** with **Codemagic**.

[Fastlane gems](https://rubygems.org/gems/fastlane) : 22Millions download 

[Fastlane github](https://github.com/fastlane/fastlane/stargazers) : Used 8.500 | Watch 715 | Star 27,392 | Fork 4,200

Pls inspire and add my modification in my dockerfile into your dockerfile :-) it's possible ?
[Image Docker-hub](https://hub.docker.com/r/jeanchristophehenry/ynov-docker-android)

**Comment by jeanchristophehenry** [comment]
**Hello**, that's a good question. I created an image in docker hub for my runners for **Android** on **gitlab**-**ci**
It's possible use **fastlane** with **Codemagic**.

[Fastlane gems](https://rubygems.org/gems/fastlane) : 22Millions download 

[Fastlane github](https://github.com/fastlane/fastlane/stargazers) : Used 8.500 | Watch 715 | Star 27,392 | Fork 4,200

Pls inspire and add my modification in my dockerfile into your dockerfile :-) it's possible ?
[Image Docker-hub](https://hub.docker.com/r/jeanchristophehenry/ynov-docker-android)

**Pull request merged**
