### PR TITLE
publish image on release

### PR DESCRIPTION
**Pull request by dulmandakh**
Let's publish docker image to Docker Hub if a GitHub release created, and have release notes attached to it. I updated publish.yaml to use v2 of build-push-action, and publish image with latest and GITHUB_REF, release tag reference, tags. Please publish a release once this merged.

Also build and test docker image only if Dockerfile changed.

### CODE REVIEW

**Comment by dulmandakh** [comment]
@gengjiawen please merge 👍

**Comment by gengjiawen** [comment]
Can you keep the config.yml and js file in this PR. I would like keep them for a while.

**Comment by dulmandakh** [comment]
@gengjiawen done, renamed .circleci/config.yaml so that it don't run in parallel with GitHub Actions.

**Comment by gengjiawen** [comment]
Also avd test looks like not added to github action.

**Pull request merged**
