### PR TITLE
bump Buck to 2020.09.09.01

### PR DESCRIPTION
**Pull request by dulmandakh**
bump Buck to 2020.09.09.01, and Android command line tools to latest version.

### CODE REVIEW

**Comment by dulmandakh** [comment]
@gengjiawen it's ready to merge. Please merge

**Review by gengjiawen — CHANGES_REQUESTED** [review]
I don't think we should bundle two ndk until the code ready. This will make the image much bigger. 

If you want to debug the new ndk, there will be many ways. I don't this will be a good idea.

**Comment by dulmandakh** [comment]
I'm doing this per discussion on https://github.com/facebook/react-native/pull/29013

**Comment by gengjiawen** [comment]
> I'm doing this per discussion on [facebook/react-native#29013](https://github.com/facebook/react-native/pull/29013)

Still the point stands. If you want to try new ndk, you can use circleCI remote ssh or personal docker image.
But put it in the default image used by many default is a terrible idea.

**Comment by dulmandakh** [comment]
ok, removed NDK 21. Bumping Buck and Android command line tools.

**Review by gengjiawen — APPROVED** [review]

**Pull request merged**
