### PR TITLE
Bump node version

### PR DESCRIPTION
**Pull request by krudos**
Bump node version to 16.x
as defined in .node-version in react native

### CODE REVIEW

**Comment by cortinico** [comment]
This was discussed here:
https://github.com/react-native-community/docker-android/issues/172#issuecomment-1143622018

I'm unsure if we want to bump Node to 16 at this stage as we won't be testing on 14 anymore. But as 18 entered LTS, it's probably worth to switch at this stage

**Comment by krudos** [comment]
current version of react native support node 16 https://github.com/facebook/react-native/blob/main/.node-version
also this tool that is use to build react native packages needs node 16 https://github.com/callstack/react-native-builder-bob

so it will be great if this could be merge

**Comment by gengjiawen** [comment]
I am inclined we directly bump to 18

**Comment by krudos** [comment]
I change it to 18

**Review by gengjiawen — APPROVED** [review]

**Comment by cortinico** [comment]
> I am inclined we directly bump to 18

I would stick to 16 actually as historically we broke builds for people on previous versions of Node if we don't run on the min supported

**Comment by gengjiawen** [comment]
> > I am inclined we directly bump to 18
> 
> I would stick to 16 actually as historically we broke builds for people on previous versions of Node if we don't run on the min supported

Node.js 16 will EOL in 2023. 18 will in 2025 with more features and newer v8.
As for old user, they can still use tagged Image as a workaround.

Also if https://github.com/react-native-community/docker-android/pull/188 got merged, they can use n to switch node version easily.

**Comment by cortinico** [comment]
As this got merged:
https://github.com/facebook/react-native/pull/35443

Please go ahead and bump to 16.x

If you need 18 -> Let's merge #188 instead

**Comment by krudos** [comment]
> As this got merged: [facebook/react-native#35443](https://github.com/facebook/react-native/pull/35443)
> 
> Please go ahead and bump to 16.x
> 
> If you need 18 -> Let's merge #188 instead

you mean bump to 18.x ?

**Comment by cortinico** [comment]
> you mean bump to 18.x ?

Nope, I meant bump to 16.x
To clarify again:

> I would stick to 16 actually as historically we broke builds for people on previous versions of Node if we don't run on the min supported

We want the docker container to run on the **minimum supported version** of Node, which was bumped from 14 -> 16.

**Review by cortinico — APPROVED** [review]

**Pull request closed without merging**
