### PR TITLE
Bump SDK version to 31

### PR DESCRIPTION
**Pull request by ShikaSD**
Required for successful builds after bumping the version in RN repo (https://github.com/facebook/react-native/pull/32606)

### CODE REVIEW

**Review by cortinico — APPROVED** [review]
LGTM. @gengjiawen what's your take on this? It's going to increase the image size, but we can remove the tools for Android `30` as soon as we're done with the bump on `react-native`.

**Review by gengjiawen — APPROVED** [review]

**Comment by ShikaSD** [comment]
@gengjiawen thanks for merging!
do you mind releasing 5.2 so we could continue iterating in RN repo?

**Comment by gengjiawen** [comment]
@cortinico can you do this, i am away from pc.

**Comment by cortinico** [comment]
> @cortinico can you do this, i am away from pc.

What's the process? Is pushing a Tag/Release sufficient to trigger a new tag on Dockerhub?

**Comment by ShikaSD** [comment]
> What's the process? Is pushing a Tag/Release sufficient to trigger a new tag on Dockerhub?

From what I see in configured Github workflows, the release should be triggered from tag

**Pull request merged**
