### PR TITLE
Upgrade NDK version

### PR DESCRIPTION
**Pull request by DragonSpirit**
Hello!
Faced with error: `No version of NDK matched the requested version 21.0.6113669`, this commit will fix it

### CODE REVIEW

**Comment by gengjiawen** [comment]
sorry, react native not support latest ndk.

**Comment by ortonomy** [comment]
@gengjiawen -- why was this closed? I don't really understand how you can say that :

> react native not support latest ndk

I am also getting exactly the same error on my CI pipeline:

`No version of NDK matched the requested version 21.0.6113669. Versions available locally: 20.1.5948944`

I am using react native `0.63.4`.

**Comment by gengjiawen** [comment]
> I don't really understand how you can say that :

I mean the react native source code.

> No version of NDK matched the requested version 21.0.6113669. Versions available locally: 20.1.5948944

Config ndk version in gradle

**Comment by ortonomy** [comment]
@gengjiawen -- this should probably be in the README for this image. Anyone who builds React native with this is going to see the same error.

**Pull request closed without merging**
