### PR TITLE
Update to Node 18.20 for Memory Leak Fix

### PR DESCRIPTION
**Pull request by TiKevin83**
Updating to Node 18.20 will fix a memory leak regression that has been affecting Jest for a while, see here for references:

https://github.com/jestjs/jest/issues/11956

https://github.com/nodejs/node/pull/51004

### CODE REVIEW

**Review by cortinico — APPROVED** [review]

**Comment by TiKevin83** [comment]
@cortinico suggestions on the failed circleci build?

**Comment by cortinico** [comment]
> @cortinico suggestions on the failed circleci build?

The CI failed because the build took more than 1 hour to complete.
In order to merge this we'll have fix the CI by either:
- Migrating to GitHub Actions
- Updating the `build` script to don't attempt to build all the architectures

**Comment by cortinico** [comment]
see also https://github.com/react-native-community/docker-android/issues/226

**Comment by TiKevin83** [comment]
@cortinico started testing a fix for #226 in #227 - it looks like the publish already has a GitHub actions workflow so it just needed the build half ported

**Comment by cortinico** [comment]
@TiKevin83 amazing so can you rebase this PR and we can merge it afterwards 👍

**Comment by TiKevin83** [comment]
> @TiKevin83 amazing so can you rebase this PR and we can merge it afterwards 👍

done - you may also want to remove the CircleCI integration that's still showing up on these PR checks

**Comment by cortinico** [comment]
> done - you may also want to remove the CircleCI integration that's still showing up on these PR checks

Yeah I already disabled it but for some reason it keep getting re-enabled

**Pull request merged**
