### PR TITLE
update sdk packages after install

### PR DESCRIPTION
**Pull request by dulmandakh**

### CODE REVIEW

**Comment by dulmandakh** [comment]
@gengjiawen please review and merge

**Comment by gengjiawen** [comment]
why change the update location ?

**Comment by dulmandakh** [comment]
We need to update packages after install. Previously, we've been running it before installing packages, which almost no-op.

**Comment by dulmandakh** [comment]
please see https://developer.android.com/studio/command-line/sdkmanager

**Comment by dulmandakh** [comment]
please see https://developer.android.com/studio/command-line/sdkmanager

**Comment by gengjiawen** [comment]
can you split buck upgrade in another PR or separate commit ?

**Comment by dulmandakh** [comment]
done, but RN master is broken

**Pull request merged**
