### PR TITLE
Bump node from 16 to 18

### PR DESCRIPTION
**Pull request by arushikesarwani94**
Since we are bumping node version in React Native from 16 to 18 in : https://github.com/facebook/react-native/pull/37709

Updating the Docker Image of Android as well to fix the Circle CI.

### CODE REVIEW

**Comment by cortinico** [comment]
This is currently blocked on CI as we need to bump the JDK version to 17 for this to work

**Comment by cortinico** [comment]
@arushikesarwani94 could you try to rebase on top of:
- https://github.com/react-native-community/docker-android/pull/203

That should unblock you for now

**Comment by arushikesarwani94** [comment]
Will rebase post #203 is landed in master.

**Review by cortinico — APPROVED** [review]

**Review by gengjiawen — APPROVED** [review]

**Comment by gengjiawen** [comment]
Thx for the contributions :)

**Comment by arushikesarwani94** [comment]
Should we release this as 9.0 ? @gengjiawen

**Pull request merged**
