### PR TITLE
github actions: publish

### PR DESCRIPTION
**Pull request by dulmandakh**
# Summary

Use GitHub Actions to publish the image to Docker Hub, instead of Circle CI.

I would like to propose to use GitHub releases feature so that users can easily see releases, and changes.

## Test Plan

Tested it on my clone at https://github.com/dulmandakh/docker-android, and published images with tags https://hub.docker.com/repository/docker/dulmandakh/react-native/tags.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by dulmandakh** [comment]
@gengjiawen do you know why no GH Actions working on this PR?

**Comment by gengjiawen** [comment]
> @gengjiawen do you know why no GH Actions working on this PR?

Before it merged, it should only work on your fork like CircleCI.

**Comment by dulmandakh** [comment]
@gengjiawen  could you please merge it, just to check if it's working

**Comment by gengjiawen** [comment]
> @gengjiawen could you please merge it, just to check if it's working

You can check on your fork here: https://github.com/dulmandakh/docker-android/runs/737179769?check_suite_focus=true.

**Comment by dulmandakh** [comment]
@gengjiawen please merge. and lets use GitHub releases feature 😉

**Comment by dulmandakh** [comment]
@gengjiawen please merge

**Comment by gengjiawen** [comment]
current circle ci can auto tag master branch with date. this looks like not doable in github action.

**Comment by gengjiawen** [comment]
also circle CI has great support for debug like ssh, this also not available in github action.

**Comment by dulmandakh** [comment]
@gengjiawen there is no way to know about changes between image tags, so let's use GitHub releases and log changes there. I find that Circle CI is not reliable, it's been failing several times lately.

**Comment by gengjiawen** [comment]
Thanks.

**Pull request merged**
