### PR TITLE
Update cmake to 3.18

### LINKED ISSUE #110: Add CMake 3.16+ to SDK
https://issuetracker.google.com/issues/152330182

### PR DESCRIPTION
**Pull request by chakrihacker**
* updated commandlinetools to latest available version
* updated cmake to latest available version

closes #110

### CODE REVIEW

**Comment by chakrihacker** [comment]
Look like google removed cmake 3.18, either we can wait till google adds it or close the pr

**Comment by gengjiawen** [comment]
> Look like google removed cmake 3.18, either we can wait till google adds it or close the pr

It's in canary channel (https://issuetracker.google.com/issues/152330182). So let's wait for a while.

**Comment by imran-iq** [comment]
:wave: Looks like its available in stable, the following works for me

```diff
@@ -5,7 +5,7 @@ LABEL Description="This image provides a base Android development environment fo
 ENV DEBIAN_FRONTEND=noninteractive
 
 # set default build arguments
-ARG SDK_VERSION=commandlinetools-linux-6609375_latest.zip
+ARG SDK_VERSION=commandlinetools-linux-7302050_latest.zip
 ARG ANDROID_BUILD_VERSION=30
 ARG ANDROID_TOOLS_VERSION=30.0.3
 ARG BUCK_VERSION=2020.10.21.01
@@ -20,7 +20,7 @@ ENV ANDROID_SDK_HOME=${ANDROID_HOME}
 ENV ANDROID_NDK=${ANDROID_HOME}/ndk/$NDK_VERSION
 ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
 
-ENV PATH=${ANDROID_NDK}:${ANDROID_HOME}/cmdline-tools/tools/bin:${ANDROID_HOME}/emulator:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:/opt/buck/bin/:${PATH}
+ENV PATH=${ANDROID_NDK}:${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/emulator:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:/opt/buck/bin/:${PATH}
 
 # Install system dependencies
 RUN apt update -qq && apt install -qq -y --no-install-recommends \
@@ -67,13 +67,14 @@ RUN curl -sS -L https://github.com/facebook/buck/releases/download/v${BUCK_VERSI
 RUN curl -sS https://dl.google.com/android/repository/${SDK_VERSION} -o /tmp/sdk.zip \
     && mkdir -p ${ANDROID_HOME}/cmdline-tools \
     && unzip -q -d ${ANDROID_HOME}/cmdline-tools /tmp/sdk.zip \
+    && mv ${ANDROID_HOME}/cmdline-tools/cmdline-tools ${ANDROID_HOME}/cmdline-tools/latest \
     && rm /tmp/sdk.zip \
     && yes | sdkmanager --licenses \
     && yes | sdkmanager "platform-tools" \
         "emulator" \
         "platforms;android-$ANDROID_BUILD_VERSION" \
         "build-tools;$ANDROID_TOOLS_VERSION" \
-        "cmake;3.10.2.4988404" \
+        "cmake;3.18.1" \
         "system-images;android-21;google_apis;armeabi-v7a" \
         "ndk;$NDK_VERSION" \
     && rm -rf ${ANDROID_HOME}/.android
```


```
docker run --rm --name rn-env react-native-community/react-native bin/sh -c "opt/android/cmake/3.18.1/bin/cmake --version"
cmake version 3.18.1-g262b901

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by chakrihacker** [comment]
Thanks @imran-iq for this, I will update this weekend

**Review by gengjiawen — APPROVED** [review]

**Comment by gengjiawen** [comment]
Thanks

**Pull request merged**
